### ISSUE TITLE
No module named 'keras' on AWS

### ISSUE THREAD

**Issue by puhach** [udacity/aind2-cnn#14]
I was trying to use AWS Notebook instance for this project as suggested in the lesson. I installed TensorFlow according to the guidelines in readme (step 5):
```
sudo python3 -m pip install -r requirements/requirements-gpu.txt
```
That seems to have worked fine. However, switching Keras backend to TensorFlow (step 6) fails.
```
KERAS_BACKEND=tensorflow python -c "from keras import backend"
```
It says "ModuleNotFoundError: No module named 'keras'". 

It needs to notice that `pip list` does not show keras or tensorflow as installed packages. When I run `sudo pip list` I can see tensorflow-gpu and Keras 2.0.2 (starting with a capital K), but not "keras" (with a small letter). Could that be a cause of the issue and how to fix it?

**Comment by ZIBOWANGKANGYU** [comment]
Hi @puhach I encountered the same problem. Did you get an answer?

**Comment by puhach** [comment]
I vaguely recall that I found two options:
1) Use EC2 instance with preinstalled tensorflow and keras libraries (search for machine learning when you choose the instance type)
2) On a fresh EC2 instance create an environment, install the libraries, and then you will need to install the kernel for Jupyter Notebook.
