### ISSUE TITLE
bug: requirements.txt install issues

### ISSUE THREAD

**Issue by kendricng** [udacity/aind2-cnn#16]
I tried installing the requirements.txt file manually via pip but wasn't able to install opencv-python.

<img width="562" alt="Screen Shot 2020-05-02 at 4 46 53 PM" src="https://user-images.githubusercontent.com/36526819/80894939-a46ee180-8c94-11ea-8990-3fecffc71e1f.png">

**Comment by ronny-udacity** [comment]
You can create conda environment with Python 3.5
