### ISSUE TITLE
It would be useful to show how the bottleneck npz files are saved

### ISSUE THREAD

**Issue by wallali** [udacity/aind2-cnn#6]
I think it would be useful to see the actual saving of the npz file to create the bottleneck features, as it completes the transfer learning picture. Otherwise the bottleneck .npz files are a bit magic ✨.

The transfer-learning/bottleneck_features.ipynb gets really close but does not include the steps to save the files to disk. Please can we have that code too?

See also: https://discussions.udacity.com/t/how-to-build-bottleneck-features/551597/2

**Comment by ghost** [comment]
Hello,
Have you found a way to look at inside the bottleneck features structure?

Thank you

**Comment by spooms11** [comment]
I have no access to the url named "https://discussions.udacity.com/t/how-to-build-bottleneck-features/551597/2". Thanks for help.
